apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: evgerher/ml-in-prod-inference:0.0.1
      name: online-inference
      ports:
        - containerPort: 5050
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "500m"
