data_path: "data/heart.csv"
split_config:
  test_ratio: 0.1
  random_state: 1337
  folds: 10
model_config:
  model_type: "RANDOM_FOREST"
  model_args:
    n_estimators: 60
    max_depth: 4
    n_jobs: -1
    random_state: 1338
feature_config:
  categorical_columns:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numeric_columns:
    - "oldpeak"
    - "chol"
    - "thalach"
    - "age"
    - "trestbps"
  categorical_policy: "ORDINAL_ENCODING"
  normalization_policy: "NONE"
  target_column: "target"