name: Python application

on:
  push:
    branches: [ master, homework1 ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ml_project
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pylint
        cd ml_project
        python -m pytest -v --cov .
        pylint --rcfile=linter.rc ml_code/